<?
$FunctionList = array();
$FunctionList['keyword'] = array( 'name' => 'keyword',
                               'operation_types' => array( 'read' ),
                               'call_method' => array( 'class' => 'nTagsFunctions',
                                                       'method' => 'fetchKeyword' ),
                               'parameter_type' => 'standard',
                               'parameters' => array( array( 'name' => 'alphabet',
                                                             'type' => 'string',
                                                             'required' => true ),
                                                      array( 'name' => 'classid',
                                                             'type' => 'mixed',
                                                             'required' => false,
                                                             'default' => false ),
                                                      array( 'name' => 'offset',
                                                             'type' => 'integer',
                                                             'required' => false,
                                                             'default' => false ),
                                                      array( 'name' => 'limit',
                                                             'type' => 'integer',
                                                             'required' => false,
                                                             'default' => false ),
                                                      array( 'name' => 'owner',
                                                             'type' => 'integer',
                                                             'required' => false,
                                                             'default' => false ),
                                                      array( 'name' => 'sort_by',
                                                             'type' => 'array',
                                                             'required' => false,
                                                             'default' => array() ),
                                                      array( 'name' => 'parent_node_id',
                                                             'type' => 'integer',
                                                             'required' => false,
                                                             'default' => false ),
                                                      array( 'name' => 'include_subtree',
                                                             'type' => 'bool',
                                                             'required' => false,
                                                             'default' => false ),
                                                     array( 'name' => 'include_duplicates',
                                                             'type' => 'bool',
                                                             'required' => false,
                                                             'default' => true ) ) );
$FunctionList['keyword_count'] = array( 'name' => 'keyword',
									   'operation_types' => array( 'read' ),
									   'call_method' => array( 'class' => 'nTagsFunctions',
															   'method' => 'fetchKeywordCount' ),
									   'parameter_type' => 'standard',
									   'parameters' => array( array( 'name' => 'alphabet',
																	 'type' => 'string',
																	 'required' => true ),
															  array( 'name' => 'classid',
																	 'type' => 'mixed',
																	 'required' => false,
																	 'default' => false ),
															  array( 'name' => 'owner',
																	 'type' => 'integer',
																	 'required' => false,
																	 'default' => false ),
															  array( 'name' => 'parent_node_id',
																	 'type' => 'integer',
																	 'required' => false,
																	 'default' => false ),
															  array( 'name' => 'include_subtree',
																	 'type' => 'bool',
																	 'required' => false,
																	 'default' => false ),
															 array( 'name' => 'include_duplicates',
																	 'type' => 'bool',
																	 'required' => false,
																	 'default' => true ) ) );
?>
